blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Monsoft-Solutions/vernisai-chat/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/Monsoft-Solutions/vernisai-chat/tree/main/docs
    about: Check our documentation for help with common issues.
